package com.penguin.cake.middleware;
public enum CakeEventType {
    ORDER_CREATED, ORDER_PAID, ORDER_BAKING_STARTED, ORDER_DISPATCHED, ORDER_COMPLETED,
    PAYMENT_CREATED, PAYMENT_NOTIFY_VERIFIED, VOUCHER_VERIFIED, VOUCHER_CONSUMED,
    TAKEOUT_ORDER_SYNCED, TAKEOUT_STATUS_PUSHED, WAREHOUSE_DAMAGE_REPORTED,
    PROCUREMENT_RECEIVED, DELIVERY_GEO_REPORTED, CAKE_STATUS_CHANGED
}
