package com.penguin.cake.domain.model;
public enum CakeLifecycleStatus {
    RAW_MATERIAL_RESERVED, BAKING, DECORATING, QUALITY_CHECK, COLD_STORAGE,
    STORE_ALLOCATED, TAKEOUT_LOCKED, DAMAGED_REPORTED, EXPIRED, SOLD, SCRAPPED
}
